"""
Django settings for hhcensus project.

Generated by 'django-admin startproject' using Django 2.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os
import platform
import socket
#print (socket.getfqdn() )

EMAIL_HOST = 'smtp.hebrewhome.org'
#EMAIL_PORT = 587  #for secure, use 25 for non secure.
#default '' EMAIL_HOST_USER = ''
#default = '' EMAIL_HOST_PASSOWRD = None
#EMAIL_USE_TLS = True #depends on email provider
#EMAIL_USE_SSL = False

DATE_INPUT_FORMATS = ['%Y-%m-%d'] #'%d-%m-%Y', '%m/%d/%Y', 

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))




# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'q2m59ym@%j4e94o5yj+a+h+s_x_^0atc=a-1gy%v9as8_!px=2'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
TEST_EMAIL_RECIPIENTS =  ['frederick.sells@RiverSpringHealth.org', 'jonathan.clark@RiverSpringHealth.org',
                                        'antonique.martin@RiverSpringHealth.org']

ALLOWED_HOSTS = ['*']

#NOTE: django simple email sender takes a list while more complex Python email modules takes a list.
# all distro lists are defined as list and converted in sending module if necessary.
# The django module is not capable of handling attachments, which are needed for Sagely
if DEBUG:
    SAGELY2_DISTRIBUTION_LIST = TEST_EMAIL_RECIPIENTS
    CENSUS_RECIPIENTS = TEST_EMAIL_RECIPIENTS
    FROM_EMAIL_ADDRESS = 'no-reply@hebrewhome.org'
    EMAIL_SUBJECT_PREFIX = '***TESTING*** '
    BED_STATUS_LOCK_HOUR = 16  #becomes 8:00 am

else: 
    EMAIL_SUBJECT_PREFIX = ''  # default='[Django] '
    CENSUS_RECIPIENTS = ['censusnotification@hebrewhome.org']   
    FROM_EMAIL_ADDRESS = 'no-reply@hebrewhome.org'
    SAGELY2_DISTRIBUTION_LIST = TEST_EMAIL_RECIPIENTS     #@todo
    BED_STATUS_LOCK_HOUR = 8  #becomes 8:00 am

 
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
   ########################################################################### 'computed_property',
    'webapp',
    'webapp.templatetags.app_filters',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'hhcensus.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'hhcensus.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases
#  r'DRIVER={SQL Server Native Client 10.0};'
#         r'SERVER=.\SQLEXPRESS;'
#         r'DATABASE=HHBedCheck;'
#          r'Trusted_Connection=yes;'



# LOCAL_SQLEXPRESS_DB = {
#     'default': {
#         'ENGINE': 'sql_server.pyodbc',
#         'NAME': 'HHBedCheck',
#         'HOST': r'.\SQLEXPRESS',
#        # 'PORT':'1433',
#         'USER': 'django',
#         'PASSWORD': 'django',
#         'OPTIONS': {
#                  'driver': 'SQL Server Native Client 10.0',                
#                  }
#         },  
#     }

# HHARSWLSQLDEV01 = {
#     'default': {
#         'ENGINE': 'sql_server.pyodbc',
#         'HOST': '.', # 'HHARSWLSQLDEV01.HHARSWLSQLDEV01',
#         'PORT': '', #'1433',
#         'NAME': 'HHdev',
#         'Trusted_Connection': 'yes;',
#         'OPTIONS': {
#             'driver': 'ODBC Driver 13 for SQL Server',  #got from list of drivers via Admin Tools/ODBC
#             'unicode_results': True,
#         },
#     },
# }

# LAPTOP = {
#     'default': {
#         'ENGINE': 'sql_server.pyodbc',
#         'HOST': '.', # 'HHARSWLSQLDEV01.HHARSWLSQLDEV01',
#         'PORT': '', #'1433',
#         'NAME': 'FredTesting',
#         'Trusted_Connection': 'yes;',
#         'OPTIONS': {
#             'driver': 'ODBC Driver 13 for SQL Server',  #got from list of drivers via Admin Tools/ODBC
#             'unicode_results': True,
#             'options': '-c search_path=mydata'
#         },
#     },
# }

HHSWLDEV02 = {
    'default': {
        'ENGINE': 'sql_server.pyodbc',
        'HOST': 'localhost', # 'HHARSWLSQLDEV01.HHARSWLSQLDEV01',
        'PORT': '', #'1433',
        'NAME': 'censusapps',
        'USER': 'hhcensus',
        'PASSWORD':'Plan-Tree-Scale-Model-Seed-9',
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',  #got from list of drivers via Admin Tools/ODBC
            'unicode_results': True,
            'options': '-c search_path=census,mydata'
        },
    },
}

DATABASES = HHSWLDEV02

# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

# LANGUAGE_CODE = 'en-us'
# 
# TIME_ZONE = 'UTC'
# 
# USE_I18N = True
# 
USE_L10N = False
# 
# USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'
